"""add_custom_report_groups

Revision ID: 0dd6941b75b8
Revises: 2f6fdb96474e
Create Date: 2026-08-30 15:48:32.415352

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd6941b75b8'
down_revision: Union[str, None] = '2f6fdb96474e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_report_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_report_groups_id'), 'custom_report_groups', ['id'], unique=False)
    op.create_index(op.f('ix_custom_report_groups_organization_id'), 'custom_report_groups', ['organization_id'], unique=False)
    op.add_column('custom_reports', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_custom_reports_group_id'), 'custom_reports', ['group_id'], unique=False)
    op.create_foreign_key(None, 'custom_reports', 'custom_report_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_reports', type_='foreignkey')
    op.drop_index(op.f('ix_custom_reports_group_id'), table_name='custom_reports')
    op.drop_column('custom_reports', 'group_id')
    op.drop_index(op.f('ix_custom_report_groups_organization_id'), table_name='custom_report_groups')
    op.drop_index(op.f('ix_custom_report_groups_id'), table_name='custom_report_groups')
    op.drop_table('custom_report_groups')
    # ### end Alembic commands ###
