"""add_custom_report_font_columns

Revision ID: 10d77a4180b0
Revises: a1b2c3d4e5f6
Create Date: 2026-08-28 09:49:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d77a4180b0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_reports', sa.Column('scalar_font_family', sa.String(length=255), server_default='Inter', nullable=False))
    op.add_column('custom_reports', sa.Column('mli_font_family', sa.String(length=255), server_default='Inter', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_reports', 'mli_font_family')
    op.drop_column('custom_reports', 'scalar_font_family')
    # ### end Alembic commands ###
