"""add_captcha_challenges

Revision ID: 2f4733872202
Revises: 613c7b3398cc
Create Date: 2026-07-31 08:11:12.886918

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4733872202'
down_revision: Union[str, None] = '613c7b3398cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captcha_challenges_id'), 'captcha_challenges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captcha_challenges_id'), table_name='captcha_challenges')
    op.drop_table('captcha_challenges')
    # ### end Alembic commands ###
