"""add_unique_user_key_and_filter_config

Revision ID: 2f6fdb96474e
Revises: 10d77a4180b0
Create Date: 2026-08-30 10:04:24.919365

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6fdb96474e'
down_revision: Union[str, None] = '10d77a4180b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_user_filter_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=True),
    sa.Column('mli_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('dynamic_value_source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['kpi_field_sub_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mli_id'], ['kpi_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['custom_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_user_filter_configurations_field_id'), 'report_user_filter_configurations', ['field_id'], unique=False)
    op.create_index(op.f('ix_report_user_filter_configurations_id'), 'report_user_filter_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_report_user_filter_configurations_kpi_id'), 'report_user_filter_configurations', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_report_user_filter_configurations_mli_id'), 'report_user_filter_configurations', ['mli_id'], unique=False)
    op.create_index(op.f('ix_report_user_filter_configurations_report_id'), 'report_user_filter_configurations', ['report_id'], unique=False)
    op.add_column('users', sa.Column('unique_user_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_unique_user_key'), 'users', ['unique_user_key'], unique=False)
    op.create_unique_constraint('uq_org_unique_user_key', 'users', ['organization_id', 'unique_user_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_org_unique_user_key', 'users', type_='unique')
    op.drop_index(op.f('ix_users_unique_user_key'), table_name='users')
    op.drop_column('users', 'unique_user_key')
    op.drop_index(op.f('ix_report_user_filter_configurations_report_id'), table_name='report_user_filter_configurations')
    op.drop_index(op.f('ix_report_user_filter_configurations_mli_id'), table_name='report_user_filter_configurations')
    op.drop_index(op.f('ix_report_user_filter_configurations_kpi_id'), table_name='report_user_filter_configurations')
    op.drop_index(op.f('ix_report_user_filter_configurations_id'), table_name='report_user_filter_configurations')
    op.drop_index(op.f('ix_report_user_filter_configurations_field_id'), table_name='report_user_filter_configurations')
    op.drop_table('report_user_filter_configurations')
    # ### end Alembic commands ###
