"""add_kpi_report_jobs

Revision ID: 3b2409fe2adf
Revises: 041_kpi_sections
Create Date: 2026-07-09 01:53:26.183065

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2409fe2adf'
down_revision: Union[str, None] = '041_kpi_sections'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_report_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('stored_path', sa.String(length=2048), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_report_jobs_id'), 'kpi_report_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_report_jobs_kpi_id'), 'kpi_report_jobs', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_kpi_report_jobs_organization_id'), 'kpi_report_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kpi_report_jobs_user_id'), 'kpi_report_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_kpi_report_jobs_year'), 'kpi_report_jobs', ['year'], unique=False)
    op.create_index(op.f('ix_export_api_tokens_id'), 'export_api_tokens', ['id'], unique=False)
    op.drop_index('ix_external_auth_configs_login_url', table_name='external_auth_configs')
    op.create_index(op.f('ix_external_auth_configs_id'), 'external_auth_configs', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_id'), 'kpi_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_entries_id'), 'kpi_entries', ['id'], unique=False)
    op.drop_index('uq_kpi_field_access_sub', table_name='kpi_field_access', postgresql_where='(sub_field_id IS NOT NULL)')
    op.drop_index('uq_kpi_field_access_whole_field', table_name='kpi_field_access', postgresql_where='(sub_field_id IS NULL)')
    op.create_index(op.f('ix_kpi_field_access_id'), 'kpi_field_access', ['id'], unique=False)
    op.drop_index('uq_kpi_field_access_by_role_sub', table_name='kpi_field_access_by_role', postgresql_where='(sub_field_id IS NOT NULL)')
    op.drop_index('uq_kpi_field_access_by_role_whole', table_name='kpi_field_access_by_role', postgresql_where='(sub_field_id IS NULL)')
    op.create_index(op.f('ix_kpi_field_access_by_role_id'), 'kpi_field_access_by_role', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_field_options_id'), 'kpi_field_options', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_field_sub_fields_id'), 'kpi_field_sub_fields', ['id'], unique=False)
    op.drop_index('ix_kpi_field_values_entry_id_field_id', table_name='kpi_field_values')
    op.create_index(op.f('ix_kpi_field_values_id'), 'kpi_field_values', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_files_id'), 'kpi_files', ['id'], unique=False)
    op.drop_index('ix_kpi_mline_cells_value_json_trgm', table_name='kpi_multi_line_cells', postgresql_using='gin')
    op.drop_index('ix_kpi_mline_cells_value_text_trgm', table_name='kpi_multi_line_cells', postgresql_using='gin')
    op.drop_index('ix_kpi_multi_line_cells_row_id_sub_field_id', table_name='kpi_multi_line_cells')
    op.drop_index('ix_kpi_multi_line_cells_row_sub_field', table_name='kpi_multi_line_cells')
    op.create_index(op.f('ix_kpi_multi_line_cells_id'), 'kpi_multi_line_cells', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_multi_line_row_access_id'), 'kpi_multi_line_row_access', ['id'], unique=False)
    op.drop_index('ix_kpi_mline_rows_search_text_trgm', table_name='kpi_multi_line_rows', postgresql_using='gin')
    op.drop_index('ix_kpi_multi_line_rows_entry_field_row_index', table_name='kpi_multi_line_rows')
    op.drop_index('ix_kpi_multi_line_rows_entry_id_field_id', table_name='kpi_multi_line_rows')
    op.create_index(op.f('ix_kpi_multi_line_rows_id'), 'kpi_multi_line_rows', ['id'], unique=False)
    op.drop_constraint('uq_kpi_odoo_config_kpi_id', 'kpi_odoo_configs', type_='unique')
    op.drop_index('ix_kpi_odoo_configs_kpi_id', table_name='kpi_odoo_configs')
    op.create_index(op.f('ix_kpi_odoo_configs_kpi_id'), 'kpi_odoo_configs', ['kpi_id'], unique=True)
    op.create_index(op.f('ix_kpi_odoo_configs_id'), 'kpi_odoo_configs', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_role_assignments_id'), 'kpi_role_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_sections_id'), 'kpi_sections', ['id'], unique=False)
    op.drop_constraint('uq_org_odoo_config_org_id', 'organization_odoo_configs', type_='unique')
    op.drop_index('ix_organization_odoo_configs_organization_id', table_name='organization_odoo_configs')
    op.create_index(op.f('ix_organization_odoo_configs_organization_id'), 'organization_odoo_configs', ['organization_id'], unique=True)
    op.create_index(op.f('ix_organization_odoo_configs_id'), 'organization_odoo_configs', ['id'], unique=False)
    op.create_index(op.f('ix_organization_roles_id'), 'organization_roles', ['id'], unique=False)
    op.drop_constraint('uq_org_storage_config_org_id', 'organization_storage_configs', type_='unique')
    op.create_index(op.f('ix_organization_storage_configs_id'), 'organization_storage_configs', ['id'], unique=False)
    op.create_index(op.f('ix_report_access_permissions_id'), 'report_access_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_report_template_fields_id'), 'report_template_fields', ['id'], unique=False)
    op.create_index(op.f('ix_report_template_kpis_id'), 'report_template_kpis', ['id'], unique=False)
    op.alter_column('report_template_text_blocks', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_report_template_text_blocks_id'), 'report_template_text_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_user_organization_roles_id'), 'user_organization_roles', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_user_organization_roles_id'), table_name='user_organization_roles')
    op.drop_index(op.f('ix_report_template_text_blocks_id'), table_name='report_template_text_blocks')
    op.alter_column('report_template_text_blocks', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_report_template_kpis_id'), table_name='report_template_kpis')
    op.drop_index(op.f('ix_report_template_fields_id'), table_name='report_template_fields')
    op.drop_index(op.f('ix_report_access_permissions_id'), table_name='report_access_permissions')
    op.drop_index(op.f('ix_organization_storage_configs_id'), table_name='organization_storage_configs')
    op.create_unique_constraint('uq_org_storage_config_org_id', 'organization_storage_configs', ['organization_id'])
    op.drop_index(op.f('ix_organization_roles_id'), table_name='organization_roles')
    op.drop_index(op.f('ix_organization_odoo_configs_id'), table_name='organization_odoo_configs')
    op.drop_index(op.f('ix_organization_odoo_configs_organization_id'), table_name='organization_odoo_configs')
    op.create_index('ix_organization_odoo_configs_organization_id', 'organization_odoo_configs', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_org_odoo_config_org_id', 'organization_odoo_configs', ['organization_id'])
    op.drop_index(op.f('ix_kpi_sections_id'), table_name='kpi_sections')
    op.drop_index(op.f('ix_kpi_role_assignments_id'), table_name='kpi_role_assignments')
    op.drop_index(op.f('ix_kpi_odoo_configs_id'), table_name='kpi_odoo_configs')
    op.drop_index(op.f('ix_kpi_odoo_configs_kpi_id'), table_name='kpi_odoo_configs')
    op.create_index('ix_kpi_odoo_configs_kpi_id', 'kpi_odoo_configs', ['kpi_id'], unique=False)
    op.create_unique_constraint('uq_kpi_odoo_config_kpi_id', 'kpi_odoo_configs', ['kpi_id'])
    op.drop_index(op.f('ix_kpi_multi_line_rows_id'), table_name='kpi_multi_line_rows')
    op.create_index('ix_kpi_multi_line_rows_entry_id_field_id', 'kpi_multi_line_rows', ['entry_id', 'field_id'], unique=False)
    op.create_index('ix_kpi_multi_line_rows_entry_field_row_index', 'kpi_multi_line_rows', ['entry_id', 'field_id', 'row_index'], unique=False)
    op.create_index('ix_kpi_mline_rows_search_text_trgm', 'kpi_multi_line_rows', [sa.text("lower(COALESCE(search_text, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_kpi_multi_line_row_access_id'), table_name='kpi_multi_line_row_access')
    op.drop_index(op.f('ix_kpi_multi_line_cells_id'), table_name='kpi_multi_line_cells')
    op.create_index('ix_kpi_multi_line_cells_row_sub_field', 'kpi_multi_line_cells', ['row_id', 'sub_field_id'], unique=False)
    op.create_index('ix_kpi_multi_line_cells_row_id_sub_field_id', 'kpi_multi_line_cells', ['row_id', 'sub_field_id'], unique=False)
    op.create_index('ix_kpi_mline_cells_value_text_trgm', 'kpi_multi_line_cells', [sa.text("lower(COALESCE(value_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('ix_kpi_mline_cells_value_json_trgm', 'kpi_multi_line_cells', [sa.text("lower(COALESCE(value_json::text, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_kpi_files_id'), table_name='kpi_files')
    op.drop_index(op.f('ix_kpi_field_values_id'), table_name='kpi_field_values')
    op.create_index('ix_kpi_field_values_entry_id_field_id', 'kpi_field_values', ['entry_id', 'field_id'], unique=False)
    op.drop_index(op.f('ix_kpi_field_sub_fields_id'), table_name='kpi_field_sub_fields')
    op.drop_index(op.f('ix_kpi_field_options_id'), table_name='kpi_field_options')
    op.drop_index(op.f('ix_kpi_field_access_by_role_id'), table_name='kpi_field_access_by_role')
    op.create_index('uq_kpi_field_access_by_role_whole', 'kpi_field_access_by_role', ['organization_role_id', 'kpi_id', 'field_id'], unique=True, postgresql_where='(sub_field_id IS NULL)')
    op.create_index('uq_kpi_field_access_by_role_sub', 'kpi_field_access_by_role', ['organization_role_id', 'kpi_id', 'field_id', 'sub_field_id'], unique=True, postgresql_where='(sub_field_id IS NOT NULL)')
    op.drop_index(op.f('ix_kpi_field_access_id'), table_name='kpi_field_access')
    op.create_index('uq_kpi_field_access_whole_field', 'kpi_field_access', ['user_id', 'kpi_id', 'field_id'], unique=True, postgresql_where='(sub_field_id IS NULL)')
    op.create_index('uq_kpi_field_access_sub', 'kpi_field_access', ['user_id', 'kpi_id', 'field_id', 'sub_field_id'], unique=True, postgresql_where='(sub_field_id IS NOT NULL)')
    op.drop_index(op.f('ix_kpi_entries_id'), table_name='kpi_entries')
    op.drop_index(op.f('ix_kpi_assignments_id'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_external_auth_configs_id'), table_name='external_auth_configs')
    op.create_index('ix_external_auth_configs_login_url', 'external_auth_configs', ['login_url'], unique=False)
    op.drop_index(op.f('ix_export_api_tokens_id'), table_name='export_api_tokens')
    op.drop_index(op.f('ix_kpi_report_jobs_year'), table_name='kpi_report_jobs')
    op.drop_index(op.f('ix_kpi_report_jobs_user_id'), table_name='kpi_report_jobs')
    op.drop_index(op.f('ix_kpi_report_jobs_organization_id'), table_name='kpi_report_jobs')
    op.drop_index(op.f('ix_kpi_report_jobs_kpi_id'), table_name='kpi_report_jobs')
    op.drop_index(op.f('ix_kpi_report_jobs_id'), table_name='kpi_report_jobs')
    op.drop_table('kpi_report_jobs')
    # ### end Alembic commands ###
