"""add allow_add_row and allow_bulk_upload to kpi_role_assignments

Revision ID: 3e4555a40966
Revises: a7d89774b06e
Create Date: 2026-07-27 18:15:20.496869

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4555a40966'
down_revision: Union[str, None] = 'a7d89774b06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_role_assignments', sa.Column('allow_add_row', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('kpi_role_assignments', sa.Column('allow_bulk_upload', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_role_assignments', 'allow_bulk_upload')
    op.drop_column('kpi_role_assignments', 'allow_add_row')
    # ### end Alembic commands ###
