"""add_custom_report_attachments

Revision ID: 3f80cbcedd24
Revises: 5f4564dab9c0
Create Date: 2026-08-07 09:12:24.867052

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f80cbcedd24'
down_revision: Union[str, None] = '5f4564dab9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_report_id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('kpi_field_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('selected_columns', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_report_id'], ['custom_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_field_id'], ['kpi_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_report_attachments_custom_report_id'), 'custom_report_attachments', ['custom_report_id'], unique=False)
    op.create_index(op.f('ix_custom_report_attachments_id'), 'custom_report_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_custom_report_attachments_kpi_field_id'), 'custom_report_attachments', ['kpi_field_id'], unique=False)
    op.create_index(op.f('ix_custom_report_attachments_kpi_id'), 'custom_report_attachments', ['kpi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_report_attachments_kpi_id'), table_name='custom_report_attachments')
    op.drop_index(op.f('ix_custom_report_attachments_kpi_field_id'), table_name='custom_report_attachments')
    op.drop_index(op.f('ix_custom_report_attachments_id'), table_name='custom_report_attachments')
    op.drop_index(op.f('ix_custom_report_attachments_custom_report_id'), table_name='custom_report_attachments')
    op.drop_table('custom_report_attachments')
    # ### end Alembic commands ###
