"""create_kpi_bulk_upload_tasks_table

Revision ID: 4598fdc00579
Revises: 3af9df048fd7
Create Date: 2026-08-27 14:34:24.592357

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4598fdc00579'
down_revision: Union[str, None] = '3af9df048fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_bulk_upload_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('import_mode', sa.String(length=20), nullable=False),
    sa.Column('match_sub_field_key', sa.String(length=100), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('rows_added', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_overridden', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['kpi_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['kpi_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_bulk_upload_tasks_entry_id'), 'kpi_bulk_upload_tasks', ['entry_id'], unique=False)
    op.create_index(op.f('ix_kpi_bulk_upload_tasks_field_id'), 'kpi_bulk_upload_tasks', ['field_id'], unique=False)
    op.create_index(op.f('ix_kpi_bulk_upload_tasks_user_id'), 'kpi_bulk_upload_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_bulk_upload_tasks_user_id'), table_name='kpi_bulk_upload_tasks')
    op.drop_index(op.f('ix_kpi_bulk_upload_tasks_field_id'), table_name='kpi_bulk_upload_tasks')
    op.drop_index(op.f('ix_kpi_bulk_upload_tasks_entry_id'), table_name='kpi_bulk_upload_tasks')
    op.drop_table('kpi_bulk_upload_tasks')
    # ### end Alembic commands ###
