"""increase_field_key_lengths

Revision ID: 51eb58e960bb
Revises: 188c3b18cb16
Create Date: 2026-07-15 14:16:28.987735

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eb58e960bb'
down_revision: Union[str, None] = '188c3b18cb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_kpi_entries_last_modified_by_user_id'), 'kpi_entries', ['last_modified_by_user_id'], unique=False)
    op.create_index(op.f('ix_kpi_entries_submitted_by_user_id'), 'kpi_entries', ['submitted_by_user_id'], unique=False)
    op.alter_column('kpi_field_sub_fields', 'key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('kpi_fields', 'key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi_fields', 'key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('kpi_field_sub_fields', 'key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_kpi_entries_submitted_by_user_id'), table_name='kpi_entries')
    op.drop_index(op.f('ix_kpi_entries_last_modified_by_user_id'), table_name='kpi_entries')
    # ### end Alembic commands ###
