"""make_kpi_id_nullable_in_custom_report_sections

Revision ID: 5f4564dab9c0
Revises: 93dd1e3f855d
Create Date: 2026-08-06 15:03:42.378960

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4564dab9c0'
down_revision: Union[str, None] = '93dd1e3f855d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_captcha_challenges_expires_at'), 'captcha_challenges', ['expires_at'], unique=False)
    op.alter_column('custom_report_sections', 'kpi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_report_sections', 'kpi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_captcha_challenges_expires_at'), table_name='captcha_challenges')
    # ### end Alembic commands ###
