"""add_dashboard_label_customizations

Revision ID: 613c7b3398cc
Revises: 3e4555a40966
Create Date: 2026-07-30 08:07:12.870847

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613c7b3398cc'
down_revision: Union[str, None] = '3e4555a40966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_label_customizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.String(length=255), nullable=True),
    sa.Column('original_label', sa.String(length=255), nullable=False),
    sa.Column('customized_label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'widget_id', 'original_label', name='uq_dashboard_widget_label')
    )
    op.create_index(op.f('ix_dashboard_label_customizations_dashboard_id'), 'dashboard_label_customizations', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_label_customizations_id'), 'dashboard_label_customizations', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_label_customizations_organization_id'), 'dashboard_label_customizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dashboard_label_customizations_widget_id'), 'dashboard_label_customizations', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_label_customizations_widget_id'), table_name='dashboard_label_customizations')
    op.drop_index(op.f('ix_dashboard_label_customizations_organization_id'), table_name='dashboard_label_customizations')
    op.drop_index(op.f('ix_dashboard_label_customizations_id'), table_name='dashboard_label_customizations')
    op.drop_index(op.f('ix_dashboard_label_customizations_dashboard_id'), table_name='dashboard_label_customizations')
    op.drop_table('dashboard_label_customizations')
    # ### end Alembic commands ###
