"""add_joined_kpis

Revision ID: 64807081ec44
Revises: 3f80cbcedd24
Create Date: 2026-08-07 10:40:44.108249

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64807081ec44'
down_revision: Union[str, None] = '3f80cbcedd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('is_joined', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('kpis', sa.Column('joined_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpis', 'joined_config')
    op.drop_column('kpis', 'is_joined')
    # ### end Alembic commands ###
