"""add_can_change_period_to_report_permissions

Revision ID: 78c3f842f1da
Revises: 0dd6941b75b8
Create Date: 2026-08-31 08:20:35.855924

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c3f842f1da'
down_revision: Union[str, None] = '0dd6941b75b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_report_assignments', sa.Column('can_change_period', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('report_access_permissions', sa.Column('can_change_period', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_access_permissions', 'can_change_period')
    op.drop_column('custom_report_assignments', 'can_change_period')
    # ### end Alembic commands ###
