"""add_mli_extraction_tables

Revision ID: 90934b98afcb
Revises: 64bb32f296e8
Create Date: 2026-08-22 12:01:55.021236

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90934b98afcb'
down_revision: Union[str, None] = '64bb32f296e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mli_extraction_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mli_extraction_symbols_id'), 'mli_extraction_symbols', ['id'], unique=False)
    op.create_table('mli_text_extraction_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_sub_field_key', sa.String(length=255), nullable=False),
    sa.Column('target_sub_field_key', sa.String(length=255), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('start_symbol', sa.String(length=20), nullable=False),
    sa.Column('end_symbol', sa.String(length=20), nullable=False),
    sa.Column('remove_delimiters_too', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('occurrence', sa.String(length=20), nullable=False),
    sa.Column('all_separator', sa.String(length=50), nullable=True),
    sa.Column('target_action', sa.String(length=30), nullable=True),
    sa.Column('remove_from_source', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['kpi_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mli_text_extraction_rules_field_id'), 'mli_text_extraction_rules', ['field_id'], unique=False)
    op.create_index(op.f('ix_mli_text_extraction_rules_id'), 'mli_text_extraction_rules', ['id'], unique=False)
    op.drop_index('ix_custom_reports_report_header_id', table_name='custom_reports')

    # Seed default symbols
    op.execute("""
        INSERT INTO mli_extraction_symbols (label, value, is_active, sort_order, created_at, updated_at)
        VALUES
            ('Opening paren',          '(',  true, 10, NOW(), NOW()),
            ('Closing paren',          ')',  true, 20, NOW(), NOW()),
            ('Opening bracket',        '[',  true, 30, NOW(), NOW()),
            ('Closing bracket',        ']',  true, 40, NOW(), NOW()),
            ('Opening brace',          '{',  true, 50, NOW(), NOW()),
            ('Closing brace',          '}',  true, 60, NOW(), NOW()),
            ('Less-than / angle open', '<',  true, 70, NOW(), NOW()),
            ('Greater-than / angle close', '>', true, 80, NOW(), NOW()),
            ('Double angle open',      '<<', true, 90, NOW(), NOW()),
            ('Double angle close',     '>>', true,100, NOW(), NOW()),
            ('Double quote',           '"',  true,110, NOW(), NOW()),
            ('Single quote',           '''', true,120, NOW(), NOW())
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_custom_reports_report_header_id', 'custom_reports', ['report_header_id'], unique=False)
    op.drop_index(op.f('ix_mli_text_extraction_rules_id'), table_name='mli_text_extraction_rules')
    op.drop_index(op.f('ix_mli_text_extraction_rules_field_id'), table_name='mli_text_extraction_rules')
    op.drop_table('mli_text_extraction_rules')
    op.drop_index(op.f('ix_mli_extraction_symbols_id'), table_name='mli_extraction_symbols')
    op.drop_table('mli_extraction_symbols')
    # ### end Alembic commands ###
