"""add_custom_report_field_config

Revision ID: 93dd1e3f855d
Revises: ad6c68d90870
Create Date: 2026-08-03 08:25:39.466288

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93dd1e3f855d'
down_revision: Union[str, None] = 'ad6c68d90870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_report_fields', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_report_fields', 'config')
    # ### end Alembic commands ###
