"""add_font_styling_to_report_headers

Revision ID: a99c0becd0b7
Revises: 633058bc2ce3
Create Date: 2026-08-18 12:03:10.210977

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99c0becd0b7'
down_revision: Union[str, None] = '633058bc2ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_report_headers', sa.Column('font_family', sa.String(length=50), nullable=True))
    op.add_column('custom_report_headers', sa.Column('font_size', sa.Integer(), nullable=True))
    op.add_column('custom_report_headers', sa.Column('text_color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_report_headers', 'text_color')
    op.drop_column('custom_report_headers', 'font_size')
    op.drop_column('custom_report_headers', 'font_family')
    # ### end Alembic commands ###
