"""add_custom_reports

Revision ID: ad6c68d90870
Revises: 2f4733872202
Create Date: 2026-08-02 00:16:28.268857

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6c68d90870'
down_revision: Union[str, None] = '2f4733872202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_reports_id'), 'custom_reports', ['id'], unique=False)
    op.create_index(op.f('ix_custom_reports_organization_id'), 'custom_reports', ['organization_id'], unique=False)
    op.create_table('custom_report_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_print', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['custom_report_id'], ['custom_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_report_id', 'user_id', name='uq_custom_report_user')
    )
    op.create_index(op.f('ix_custom_report_assignments_custom_report_id'), 'custom_report_assignments', ['custom_report_id'], unique=False)
    op.create_index(op.f('ix_custom_report_assignments_id'), 'custom_report_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_custom_report_assignments_user_id'), 'custom_report_assignments', ['user_id'], unique=False)
    op.create_table('custom_report_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_report_id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('custom_header', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_report_id'], ['custom_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_report_sections_custom_report_id'), 'custom_report_sections', ['custom_report_id'], unique=False)
    op.create_index(op.f('ix_custom_report_sections_id'), 'custom_report_sections', ['id'], unique=False)
    op.create_index(op.f('ix_custom_report_sections_kpi_id'), 'custom_report_sections', ['kpi_id'], unique=False)
    op.create_table('custom_report_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_report_id', sa.Integer(), nullable=False),
    sa.Column('custom_report_section_id', sa.Integer(), nullable=False),
    sa.Column('kpi_field_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_report_id'], ['custom_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_report_section_id'], ['custom_report_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_field_id'], ['kpi_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_report_fields_custom_report_id'), 'custom_report_fields', ['custom_report_id'], unique=False)
    op.create_index(op.f('ix_custom_report_fields_custom_report_section_id'), 'custom_report_fields', ['custom_report_section_id'], unique=False)
    op.create_index(op.f('ix_custom_report_fields_id'), 'custom_report_fields', ['id'], unique=False)
    op.create_index(op.f('ix_custom_report_fields_kpi_field_id'), 'custom_report_fields', ['kpi_field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_report_fields_kpi_field_id'), table_name='custom_report_fields')
    op.drop_index(op.f('ix_custom_report_fields_id'), table_name='custom_report_fields')
    op.drop_index(op.f('ix_custom_report_fields_custom_report_section_id'), table_name='custom_report_fields')
    op.drop_index(op.f('ix_custom_report_fields_custom_report_id'), table_name='custom_report_fields')
    op.drop_table('custom_report_fields')
    op.drop_index(op.f('ix_custom_report_sections_kpi_id'), table_name='custom_report_sections')
    op.drop_index(op.f('ix_custom_report_sections_id'), table_name='custom_report_sections')
    op.drop_index(op.f('ix_custom_report_sections_custom_report_id'), table_name='custom_report_sections')
    op.drop_table('custom_report_sections')
    op.drop_index(op.f('ix_custom_report_assignments_user_id'), table_name='custom_report_assignments')
    op.drop_index(op.f('ix_custom_report_assignments_id'), table_name='custom_report_assignments')
    op.drop_index(op.f('ix_custom_report_assignments_custom_report_id'), table_name='custom_report_assignments')
    op.drop_table('custom_report_assignments')
    op.drop_index(op.f('ix_custom_reports_organization_id'), table_name='custom_reports')
    op.drop_index(op.f('ix_custom_reports_id'), table_name='custom_reports')
    op.drop_table('custom_reports')
    # ### end Alembic commands ###
