"""add_can_download_word_to_report_permissions

Revision ID: df258311552f
Revises: 048_rights_mgmt
Create Date: 2026-09-09 07:43:53.262915

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df258311552f'
down_revision: Union[str, None] = '048_rights_mgmt'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if inspector.has_table("custom_report_assignments"):
        cra_cols = [c["name"] for c in inspector.get_columns("custom_report_assignments")]
        if "can_download_word" not in cra_cols:
            op.add_column('custom_report_assignments', sa.Column('can_download_word', sa.Boolean(), server_default='false', nullable=False))
        if "can_load_lms" not in cra_cols:
            op.add_column('custom_report_assignments', sa.Column('can_load_lms', sa.Boolean(), server_default='false', nullable=False))

    if inspector.has_table("report_access_permissions"):
        rap_cols = [c["name"] for c in inspector.get_columns("report_access_permissions")]
        if "can_download_word" not in rap_cols:
            op.add_column('report_access_permissions', sa.Column('can_download_word', sa.Boolean(), server_default='false', nullable=False))
        if "can_load_lms" not in rap_cols:
            op.add_column('report_access_permissions', sa.Column('can_load_lms', sa.Boolean(), server_default='false', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_access_permissions', 'can_load_lms')
    op.drop_column('report_access_permissions', 'can_download_word')
    op.drop_column('custom_report_assignments', 'can_load_lms')
    op.drop_column('custom_report_assignments', 'can_download_word')
    # ### end Alembic commands ###
